<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>gk-cloud-adminportal-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\orchestration\GoldKiosk.ServiceDefaults\GoldKiosk.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\shared\GoldKiosk.Infrastructure\GoldKiosk.Infrastructure.csproj" />
  </ItemGroup>

</Project>
