-- ============================================================================
-- 0031_tables_activation_invites_api.sql
-- Adds the three tables needed by the new Admin Dashboard onboarding flow:
--
--   1. identity.activation_keys
--        Generated by the CRM at partner-onboarding time and pushed here over
--        the provisioning API. Stores the SHA-256 hash only; cleartext lives
--        only in the email we sent the primary admin. Consumed (one-time) when
--        the admin first signs in via the "Activate with key" form.
--
--   2. identity.user_invitations
--        Once activated, the primary admin invites employees from inside the
--        Admin Dashboard. Each invite carries a one-time token + the role the
--        invitee will receive on accept.
--
--   3. integration.partner_api_credentials
--        Partner-generated app_id + app_key pairs they use to call Gold Kiosk
--        REST APIs from their own backend. app_id is public; app_key is hashed.
--        Distinct from integration.integration_credentials (which is OUTBOUND
--        from Gold Kiosk to upstream providers like Cashfree, Onfido, etc.).
--
-- Idempotent. Safe to re-run.
-- ============================================================================

\echo '── 0031 activation keys + invitations + partner API credentials ──'

-- ─── identity.activation_keys ───────────────────────────────────────────────
-- One live key per tenant; previous keys must be revoked before issuing a new.
-- key_hash = digest(cleartext, 'sha256'). Cleartext never persisted.
-- key_prefix = first 4-char hex group of the cleartext, kept for UI display
--   (e.g. "AIKI-7F2A" — lets the CRM screen show "AIKI-7F2A-****-****" without
--    needing the cleartext, while making forensic lookups easier).
CREATE TABLE IF NOT EXISTS identity.activation_keys (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           uuid NOT NULL,
    key_prefix          citext NOT NULL,                       -- "AIKI-7F2A" — public-safe display fragment
    key_hash            bytea NOT NULL,                        -- sha256(full cleartext key)
    issued_to_email     public.domain_email NOT NULL,          -- the admin email the key was emailed to; must match at signin
    issued_at           timestamptz NOT NULL DEFAULT now(),
    issued_by_actor     text NOT NULL DEFAULT 'crm',           -- which system issued it (CRM, manual rotation, etc.)
    expires_at          timestamptz NOT NULL,                  -- conventionally issued_at + 30 days
    consumed_at         timestamptz NULL,                      -- set when the admin uses it to sign up
    consumed_by_user_id uuid NULL,                             -- the identity.users row the activation created
    revoked_at          timestamptz NULL,                      -- set when re-issued or compromised
    revoked_reason      text NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_activation_keys__tenants  FOREIGN KEY (tenant_id)           REFERENCES tenancy.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_activation_keys__users    FOREIGN KEY (consumed_by_user_id) REFERENCES identity.users(id),
    CONSTRAINT uq_activation_keys__hash     UNIQUE (key_hash),
    CONSTRAINT ck_activation_keys__prefix   CHECK (key_prefix ~ '^AIKI-[0-9A-F]{4}$'),
    CONSTRAINT ck_activation_keys__lifecycle CHECK (
        -- if revoked, no consumption (and vice versa)
        NOT (consumed_at IS NOT NULL AND revoked_at IS NOT NULL)
    )
);

-- One LIVE key per tenant (uniqueness predicate-indexed on the "active" set)
CREATE UNIQUE INDEX IF NOT EXISTS ux_activation_keys__live_per_tenant
    ON identity.activation_keys(tenant_id)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_activation_keys__expiring
    ON identity.activation_keys(expires_at)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_activation_keys__email
    ON identity.activation_keys(issued_to_email);

COMMENT ON TABLE identity.activation_keys IS
    'Primary-admin tenant activation keys (AIKI-XXXX-XXXX-XXXX). Issued by the CRM, '
    'consumed once at admin signup. Cleartext is never stored.';

-- ─── identity.user_invitations ──────────────────────────────────────────────
-- Created by the primary admin (or any user with the manage_users permission)
-- when inviting an employee. Carries the role the invitee will assume on accept.
CREATE TABLE IF NOT EXISTS identity.user_invitations (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           uuid NOT NULL,
    invitee_email       public.domain_email NOT NULL,
    invitee_first_name  text NULL,
    invitee_last_name   text NULL,
    role_id             uuid NOT NULL,                         -- the role the invitee will receive
    store_id            uuid NULL,                             -- optional store-scoped invite
    token_hash          bytea NOT NULL,                        -- sha256(invite_token) — token only in the email link
    invited_by_user_id  uuid NOT NULL,
    invited_at          timestamptz NOT NULL DEFAULT now(),
    expires_at          timestamptz NOT NULL,                  -- conventionally invited_at + 7 days
    accepted_at         timestamptz NULL,
    accepted_user_id    uuid NULL,                             -- the identity.users row created on accept
    revoked_at          timestamptz NULL,
    revoked_reason      text NULL,
    resent_count        integer NOT NULL DEFAULT 0,
    last_resent_at      timestamptz NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_invitations__tenants  FOREIGN KEY (tenant_id)        REFERENCES tenancy.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_invitations__roles    FOREIGN KEY (role_id)          REFERENCES identity.roles(id),
    CONSTRAINT fk_user_invitations__inviter  FOREIGN KEY (invited_by_user_id) REFERENCES identity.users(id),
    CONSTRAINT fk_user_invitations__accepted FOREIGN KEY (accepted_user_id) REFERENCES identity.users(id),
    CONSTRAINT uq_user_invitations__token    UNIQUE (token_hash),
    CONSTRAINT ck_user_invitations__lifecycle CHECK (
        NOT (accepted_at IS NOT NULL AND revoked_at IS NOT NULL)
    )
);

-- One LIVE invite per (tenant, email)
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_invitations__live_per_email
    ON identity.user_invitations(tenant_id, invitee_email)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_user_invitations__tenant_pending
    ON identity.user_invitations(tenant_id, invited_at DESC)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

COMMENT ON TABLE identity.user_invitations IS
    'Employee invitations sent from inside the Admin Dashboard. One-time token, '
    '7-day expiry, single role + optional store scope.';

-- ─── integration.partner_api_credentials ────────────────────────────────────
-- Partner-generated API credentials for INBOUND calls into Gold Kiosk's REST
-- API. Distinct from integration.integration_credentials (outbound only).
--
-- app_id is shown in cleartext (it's the public half of the pair).
-- app_key_hash is sha256 of the cleartext key; cleartext is shown ONCE at
-- generation and not stored.
-- scopes is a jsonb array of permission codes (e.g. ["transactions:read",
-- "kiosks:read", "customers:read"]).
CREATE TABLE IF NOT EXISTS integration.partner_api_credentials (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id            uuid NOT NULL,
    label                text NOT NULL,                        -- partner-chosen display name e.g. "Core banking sync"
    app_id               citext NOT NULL,                      -- public id, e.g. "gk_live_a4f2c19b3e8d"
    app_key_hash         bytea NOT NULL,                       -- sha256(cleartext app_key)
    app_key_prefix       citext NOT NULL,                      -- first 8 chars of cleartext, for UI display ("sk_live_a4f2…")
    scopes               jsonb NOT NULL DEFAULT '[]'::jsonb,   -- array of permission codes
    rate_limit_per_min   integer NOT NULL DEFAULT 600,
    allowed_ips_cidr     jsonb NULL,                           -- optional ip allow-list; null = no restriction
    environment          text NOT NULL DEFAULT 'live',         -- live | test
    created_by_user_id   uuid NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    last_used_at         timestamptz NULL,
    last_used_ip         inet NULL,
    expires_at           timestamptz NULL,                     -- optional expiry; null = does not expire
    revoked_at           timestamptz NULL,
    revoked_reason       text NULL,
    rotated_from_id      uuid NULL,                            -- chain for rotation history
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_partner_api_credentials__tenants FOREIGN KEY (tenant_id)          REFERENCES tenancy.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_partner_api_credentials__users   FOREIGN KEY (created_by_user_id) REFERENCES identity.users(id),
    CONSTRAINT fk_partner_api_credentials__rotated FOREIGN KEY (rotated_from_id)    REFERENCES integration.partner_api_credentials(id),
    CONSTRAINT uq_partner_api_credentials__app_id  UNIQUE (app_id),
    CONSTRAINT uq_partner_api_credentials__hash    UNIQUE (app_key_hash),
    CONSTRAINT ck_partner_api_credentials__env     CHECK (environment IN ('live','test')),
    CONSTRAINT ck_partner_api_credentials__app_id  CHECK (app_id ~ '^gk_(live|test)_[0-9a-f]{12,32}$')
);

CREATE INDEX IF NOT EXISTS ix_partner_api_credentials__tenant_live
    ON integration.partner_api_credentials(tenant_id, created_at DESC)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_partner_api_credentials__app_id_live
    ON integration.partner_api_credentials(app_id)
    WHERE revoked_at IS NULL;

COMMENT ON TABLE integration.partner_api_credentials IS
    'Partner-generated app_id/app_key pairs for INBOUND API access. Each partner '
    'may hold many (per integration, per environment). app_key cleartext is '
    'returned ONCE at generation and not stored.';

\echo '✓ 0031 done.'
